# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# GetSincastAssays
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' Extract the \code{SincastAssays} object from a \code{Sincast} appended \code{Seurat} object.
#'
#' To be added.
#'
#' @param object A \code{Seurat} object.
#' @param assay Either \code{"both"}, \code{"pseudobulk"} or \code{"imputation"} indicating
#' which specific \code{Sincast} assay to extract.
#'
#' @return Depending on the \code{assay} argument, can be either type of a \code{Sicast} assay,
#' or a \code{SincastAssays} object containing both the types.
#'
#' @family SincastAssays related methods
#'
#' @export
#' @rdname GetSincastAssays
#' @aliases Sincast, SincastAssays, Seurat
setGeneric("GetSincastAssays", function(object, assay = c("both", "pseudobulk", "imputation"), ...) {
  standardGeneric("GetSincastAssays")
})

#' @rdname GetSincastAssays
setMethod("GetSincastAssays", "Seurat", function(object,
                                                 assay = c("both", "pseudobulk", "imputation"), ...) {
  # Check the validity of the "Sincast" object in "Seurat"'s "misc" slot.
  test.SincastObject <- Sincast::CheckSincastObject(object, complete = FALSE)

  # If the "Sincast" object is missing, or invalid, return a NULL
  if (any(test.SincastObject)) {
    out <- NULL
  } else {
    assay <- match.arg(assay)
    out <- Sincast::GetSincastObject(object)@SincastAssays
    test.SincastAssays <- validObject(out, test = TRUE)

    silent <- all(test.SincastAssays %in% c("Valid", "Empty"))
    if (assay == "pseudobulk") {
      out <- out@pseudobulk
      if(test.SincastAssays["pseudobulk"] == "Valid"){
        silent = TRUE
      }
    }

    if (assay == "imputation") {
      out <- out@imputation
      if(test.SincastAssays["imputation"] == "Valid"){
        silent = TRUE
      }
    }

    if(!silent){
      message(
        "GetSincastAssays: Check 'SincastAssays': ",
        "\n \t 'pseudobulk' assay: ", test.SincastAssays["pseudobulk"],
        "; 'imputation' assay: ", test.SincastAssays["imputation"], collapse = ''
      )
    }

  }

  out
})


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# GetSincastAssays<-
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' Setter function for \code{GetSincastAssays}.
#'
#' To be added.
#'
#' @param object A \code{Seurat} object.
#' @param assay Either \code{"both"}, \code{"pseudobulk"} or \code{"imputation"} indicating
#' which specific \code{Sincast} assay to be set.
#'
#' @return A \code{Seurat} object with updated \code{Sincast} assays.
#'
#' @family SincastAssays related methods
#'
#' @export
#' @rdname GetSincastAssays
#' @aliases Sincast, SincastAssays, Seurat
setGeneric("GetSincastAssays<-", function(object,
                                          assay = c("both", "pseudobulk", "imputation"), value, ...) {
  standardGeneric("GetSincastAssays<-")
})

#' @rdname GetSincastAssays
setMethod("GetSincastAssays<-", "Seurat", function(object,
                                                 assay = c("both", "pseudobulk", "imputation"), value, ...) {
  # Check the validity of the "Sincast" object in "Seurat"'s "misc" slot.
  Sincast::CheckSincastObject(object, complete = FALSE, test = FALSE)

  assay <- match.arg(assay)
  SincastObject <- Sincast::GetSincastObject(object)

  if (assay == "both") {
    SincastObject@SincastAssays <- value
  }
  if (assay == "pseudobulk") {
    SincastObject@SincastAssays@pseudobulk <- value
  }
  if (assay == "imputation") {
    SincastObject@SincastAssays@imputation <- value
  }

  GetSincastObject(object) <- SincastObject

  object
})


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# CleanSincastAssays
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' Remove unwanted or invalid elements (i.e, non-\code{Seurat} object) in \code{Sincast} assays
#' \code{pseudobulk} and \code{imputation} embedded in \code{Sincast} appended \code{Seurat} object.
#'
#' To be added.
#'
#' @param object A \code{Sincast} appended \code{Seurat} object.
#' @param clean.up Either \code{"None"}, \code{"All"}, \code{"pseudobulk"} or \code{"imputation"} indicating whether to clean up
#' the \code{SincastAssays} object or clean up a specific \code{Sincast} assay as proposed.
#' @param remove.invalid Logical; if TRUE, check the validity of the existing \code{Sincast} assays and
#' remove invalid ones (e.g, \code{Seurat} objects not generated by \code{Sincast} functions).
#'
#' @return A \code{Seurat} object with updated \code{Sincast} assays.
#'
#' @family SincastAssays related methods
#'
#' @export
#' @rdname CleanSincastAssays
#' @aliases Sincast, SincastAssays, Seurat
setGeneric("CleanSincastAssays", function(object,
                                          remove.id.pseudobulk = NULL,
                                          remove.id.imputation = NULL,
                                          clean.up = c("none", "all", "pseudobulk", "imputation"),
                                          remove.invalid = TRUE,
                                          ...) {
  standardGeneric("CleanSincastAssays")
})

#' @rdname CleanSincastAssays
setMethod("CleanSincastAssays", "Seurat", function(object,
                                                   clean.up = c("none", "all", "pseudobulk", "imputation"),
                                                   remove.invalid = TRUE, ...) {
  SincastObject <- Sincast::GetSincastObject(object)

  ret.summary <- FALSE

  if (is.null(SincastObject)) {
    if (remove.invalid) {
      message(
        "CleanSincastAssays: Add (replace with) a new 'Sincast' object as 'remove.invalid = TRUE'."
      )
      SincastObject <- Sincast::CreateSincastObject(
        by = "CleanSincastAssays",
        command = deparse(match.call())
      )
    } else {
      message(
        "CleanSincastAssays: Set 'remove.invalid' = TRUE to add (replace with) a new 'Sincast' object."
      )
    }
  } else {
    SincastAssays <- SincastObject@SincastAssays
    test.SincastAssays <- validObject(SincastAssays, test = T)
    message(
      "CleanSincastAssays: Before clean up: ",
      "\n \t 'pseudobulk' assay: ", test.SincastAssays["pseudobulk"],
      "; 'imputation' assay: ", test.SincastAssays["imputation"]
    )

    # Clean up a assay (assays)
    if (!is.null(clean.up)) {
      # Check the validity of clean.up
      clean.up <- match.arg(clean.up)
      if (clean.up == "all") {
        SincastAssays <- new("SincastAssays")
      } else if (clean.up == "pseudobulk") {
        SincastAssays@pseudobulk <- NULL
      } else if (clean.up == "imputation") {
        SincastAssays@imputation <- NULL
      }
    }

    # Check and remove invalid elements in "Sincast" assays.
    test.SincastAssays <- validObject(SincastAssays, test = T)
    is.pseudobulk.valid <- test.SincastAssays["pseudobulk"] %in% c("Valid","Empty")
    is.imputation.valid <- test.SincastAssays["imputation"] %in% c("Valid","Empty")

    # Clean up the "pseudobulk" assay
    if (!is.pseudobulk.valid) {
      if (remove.invalid) {
        message(
          "CleanSincastAssays: Remove invalid 'pseudobulk' assay  as 'remove.invalid = TRUE'."
        )
        SincastAssays@pseudobulk <- NULL
        test.SincastAssays["pseudobulk"] <- "Empty"
      } else {
        message(
          "CleanSincastAssays: ", "the 'pseudobulk' assay is invalid. Consider replace it by setting 'remove.invalid = TRUE'."
        )
      }
    }

    # Clean up the "imputation" assay
    if (!is.imputation.valid) {
      if (remove.invalid) {
        message(
          "CleanSincastAssays: Remove invalid 'imputation' assay as 'remove.invalid = TRUE'."
        )
        SincastAssays@imputation <- NULL
        test.SincastAssays["imputation"] <- "Empty"
      } else {
        message(
          "CleanSincastAssays: ", "the 'imputation' assay is invalid. Consider replace it by setting 'remove.invalid = TRUE'."
        )
      }
    }

    message(
      "CleanSincastAssays: After clean up: ",
      "\n \t 'pseudobulk' assay: ", test.SincastAssays["pseudobulk"],
      "; 'imputation' assay: ", test.SincastAssays["imputation"]
    )

    SincastObject@SincastAssays <- SincastAssays
  }

  # Update the "Sincast" object
  GetSincastObject(object) <- SincastObject


  object
})
