# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Sincast object, could be used
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Sincast <- setClass(
#   Class = "Sincast",
#   contains = "Seurat"
# )
#
# setAs("Seurat", "Sincast", function(from, to) {
#   arguments <- paste(slotNames(from), "=from@", slotNames(from), sep = "", collapse = ",")
#   text2expr <- paste("Sincast(", arguments, ")", sep = "")
#   eval(parse(text = text2expr))
# })

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# S4 class definition
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
NullSeurat <- setClassUnion(
  name = "NullSeurat",
  members = c("NULL", "Seurat")
)


#' An S4 class to store \code{Sincast} aggregation or imputation results.
#'
#' To be added.
#'
#' @slot pseudobulk A list of \code{Seurat} object storing aggregated pseudobulk.
#' @slot imputation A list of \code{Seurat} object storing imputed single cells.
#'
#' @family SincastAssays related methods
#'
#' @name SincastAssays-class
#' @rdname SincastAssays-class
#' @aliases Sincast, SincastAssays
SincastAssays <- setClass(
  Class = "SincastAssays",
  slots = list(
    pseudobulk = "NullSeurat",
    imputation = "NullSeurat"
  )
)

#' SincastAssays Object Validity
#'
#' Validation of \code{SincastAssays} objects is handled by \code{\link[methods]{validObject}}.
#'
#' @name SincastAssays-validity
#' @rdname SincastAssays-class
#' @aliases Sincast, SincastAssays
setValidity(
  Class = "SincastAssays",
  method = function(SincastAssays) {
    test <- function(assay) {
      Out <- "Valid"
      if (is.null(assay)) {
        out <- "Empty"
      } else {
        SincastToken <- Seurat::Misc(assay, slot = "SincastToken")
        if (!is(SincastToken, "SincastToken")) out <- "Sincast token is either missing or invalid"
      }
      out
    }

    test.result <- c(pseudobulk = "Valid", imputation = "Valid")
    test.result["pseudobulk"] <- test(SincastAssays@pseudobulk)
    test.result["imputation"] <- test(SincastAssays@imputation)


    test.result
  }
)

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# CreateSincastAssays
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' Add a \code{SincastAssays} object to \code{Seurat}'s \code{misc} slot.
#'
#' To be added.
#'
#' @param object A \code{Seurat} object.
#' @param replace Whether to replace the existing 'SincastAssays' object, or check the validity of the existing
#' \code{Sincast} assays and remove invalid ones (e.g, \code{Seurat} objects not generated by \code{Sincas}t functions).
#'
#' @return An updated \code{Seurat} object with an additional \code{SincastAssays} object in the \code{misc} slot.
#'
#' @family SincastAssays related methods
#'
#' @export
#' @rdname CreateSincastAssays
#' @aliases Sincast, SincastAssays, Seurat
setGeneric("CreateSincastAssays", function(object, replace = c("None", "All", "invalid"), ...) standardGeneric("CreateSincastAssays"))

#' @rdname CreateSincastAssays
setMethod("CreateSincastAssays", "Seurat", function(object, replace = c("None", "All", "invalid")) {
  if (is.null(Seurat::Misc(object, slot = "SincastAssays"))) {
    Seurat::Misc(object, slot = "SincastAssays") <- new("SincastAssays")
    Seurat::Misc(object, slot = "SincastToken") <- GenerateSincastToken()
  } else {
    message("CreateSincastAssays: 'SincastAssays' object already exists. Check if it's valid.")
    object <- CleanSincastAssays(object, remove.invalid = replace == "invalid")
    if (replace == "All") {
      message("CreateSincastAssays: replacing the existing 'SincastAssays' object.")
      suppressWarnings(Seurat::Misc(object, slot = "SincastAssays") <- new("SincastAssays"))
    }
  }

  object
})


# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# CleanSincastAssays
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' Remove unwanted or invalid elements (i.e, non-\code{Seurat} object) in \code{Sincast} assays
#' \code{pseudobulk} and \code{imputation} embedded in \code{Seurat::MISC(object, slot = "SincastAssays")}.
#'
#' To be added.
#'
#' @param object A \code{Seurat} object with an additional \code{SincastAssays} object in the \code{misc} slot.
#' @param clean.up Either "None", "All", "pseudobulk" or "imputation" indicating whether to clean up
#' the \code{SincastAssays} object or clean up a specific \code{Sincast} assay as proposed.
#' @param remove.invalid Logical. Whether to check the validity of the existing \code{Sincast} assays and
#' remove invalid ones (e.g, \code{Seurat} objects not generated by \code{Sincast} functions).
#'
#' @return An updated \code{Seurat} object with an additional \code{SincastAssays} object in the \code{misc} slot.
#'
#' @family SincastAssays related methods
#'
#' @export
#' @rdname CleanSincastAssays
#' @aliases Sincast, SincastAssays, Seurat
setGeneric("CleanSincastAssays", function(object,
                                          remove.id.pseudobulk = NULL,
                                          remove.id.imputation = NULL,
                                          clean.up = c("None", "All", "pseudobulk", "imputation"),
                                          remove.invalid = TRUE,
                                          ...) {
  standardGeneric("CleanSincastAssays")
})

#' @rdname CleanSincastAssays
setMethod("CleanSincastAssays", "Seurat", function(object,
                                                   clean.up = c("None", "All", "pseudobulk", "imputation"),
                                                   remove.invalid = TRUE) {
  SincastAssays <- Seurat::Misc(object, slot = "SincastAssays")
  ret.summary <- FALSE

  if (is.null(SincastAssays)) {
    if (remove.invalid) {
      message("CleanSincastAssays: 'SincastAssays' object does not exists. Add a 'SincastAssays' object.")
      SincastAssays <- new("SincastAssays")
    } else {
      message("CleanSincastAssays: 'SincastAssays' object does not exists.")
    }
  } else if (is(SincastAssays, "SincastAssays")) {
    # Clean up a assay (assays)
    if (!is.null(clean.up)) {
      # Check the validity of clean.up
      clean.up <- match.arg(clean.up)
      if (clean.up == "All") {
        SincastAssays <- new("SincastAssays")
      } else if (clean.up == "pseudobulk") {
        SincastAssays@pseudobulk <- NULL
      } else if (clean.up == "imputation") {
        SincastAssays@imputation <- NULL
      }
    }

    # Check and remove invalid elements in Sincast assays.
    test.result <- validObject(
      SincastAssays,
      test = T
    )
    all.valid <- TRUE
    is.pseudobulk.valid <- test.result$pseudobulk == "valid"
    is.imputation.valid <- test.result$imputation == "valid"

    if (is.pseudobulk.valid) {
      if (remove.invalid) {
        message(
          "CleanSincastAssays: Remove invalid 'pseudobulk' assay."
        )
        SincastAssays@pseudobulk <- NULL
        test.result$pseudobulk <- "Empty"
      } else {
        message(
          "CleanSincastAssays: ", "the 'pseudobulk' assay is invalid. Consider remove it."
        )
      }
      all.valid <- FALSE
    }

    if (is.imputation.valid) {
      if (remove.invalid) {
        message(
          "CleanSincastAssays: Remove invalid 'imputation' assay."
        )
        SincastAssays@imputation <- NULL
        test.result$imputation <- "Empty"
      } else {
        message(
          "CleanSincastAssays: ", "the 'imputation' assay is invalid. Consider remove it."
        )
      }
      all.valid <- FALSE
    }
    if (all.valid) {
      message("CleanSincastAssays: Valid.")
    }
    ret.summary <- TRUE
  } else {
    if (remove.invalid) {
      message("CleanSincastAssays: Replacing an unknown 'SincastAssays' object.")
      SincastAssays <- new("SincastAssays")
    } else {
      message("CleanSincastAssays: There is an unknown ’SincastAssays‘ object. Consider remove it.")
    }
  }

  # Update
  suppressWarnings(Seurat::Misc(object, slot = "SincastAssays") <- SincastAssays)
  SincastToken <- Seurat::Misc(object, slot = "SincastToken")
  if (is.null(SincastToken)) {
    SincastToken <- GenerateSincastToken()
  } else if (!is(SincastToken, "SincastToken")) {
    SincastToken <- GenerateSincastToken()
  }
  suppressWarnings(Seurat::Misc(object, slot = "SincastToken") <- SincastToken)

  if (ret.summary) {
    message(
      "CleanSincastAssays: 'pseudobulk' assay: ", test.result$pseudobulk,
      "; 'imputation' assay: ", test.result$imputation
    )
  }

  object
})
